package seeds

import (
	"log"
	"studsphere/backend/models"
	"time"

	"gorm.io/gorm"
)

type CurriculumSemester struct {
	Semester int      `json:"semester"`
	Title    string   `json:"title"`
	Subtitle string   `json:"subtitle"`
	Subjects []string `json:"subjects"`
}

type CareerOpportunity struct {
	Title string `json:"title"`
	Icon  string `json:"icon"`
	Color string `json:"color"`
}

func SeedExams(db *gorm.DB) error {
	exams := []models.Exam{
		{
			Slug:         "neb-class-12",
			Title:        "NEB Class 12 Annual Examination 2081",
			Board:        "NEB (National Examination Board)",
			Badges:       marshalJSON([]string{"BOARD EXAM", "UPCOMING"}),
			Level:        "+2 / Intermediate",
			Type:         "Board Exam",
			ExamDate:     "Baishakh 14, 2082 (Apr 27, 2025)",
			ExamDateAD:   time.Date(2025, 4, 27, 0, 0, 0, 0, time.UTC),
			FormDeadline: "Magh 20, 2081 (Feb 3, 2025)",
			Fee:          "NPR 600",
			Highlights:   marshalJSON([]string{"Official routine published", "Form filling active", "Admit cards by Chaitra end"}),
			Description:  "Annual final examination for Grade 12 students across Nepal.",
			Status:       "active",
			ImageUrl:     "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=800",
			University:   "National Board",
			Faculty:      "All Streams",
			NepaliDate:   "Asoj 01, 2082",
			Overview:     "The final gateway for secondary education in Nepal. Mandatory for higher studies.",
			Weightage:    marshalJSON([]map[string]interface{}{{"label": "Theory", "marks": 75, "color": "bg-brand-500", "width": "75%"}, {"label": "Practical", "marks": 25, "color": "bg-emerald-500", "width": "25%"}}),
		},
		{
			Slug:         "ioe-entrance",
			Title:        "IOE Entrance Examination 2081",
			Board:        "Institute of Engineering, TU",
			Badges:       marshalJSON([]string{"ENTRANCE", "POPULAR"}),
			Level:        "Undergraduate (Bachelor)",
			Type:         "Entrance Exam",
			ExamDate:     "Jestha 2082 (May/June 2025)",
			ExamDateAD:   time.Date(2025, 6, 1, 0, 0, 0, 0, time.UTC),
			FormDeadline: "Chaitra 2081 (Mar/Apr 2025)",
			Fee:          "NPR 2000",
			Highlights:   marshalJSON([]string{"BE Computer, Civil, Arch", "140 MCQ Questions", "Pulchowk, Thapathali seats"}),
			Description:  "Entrance exam for BE programs at IOE constituent campuses.",
			Status:       "upcoming",
			ImageUrl:     "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=800",
			University:   "Tribhuvan University",
			Faculty:      "IOE Pulchowk",
			NepaliDate:   "Mangsir 25, 2082",
			Overview:     "The gateway to Pulchowk Campus and other constituent engineering colleges. Get details on syllabus, shifts, and admit cards.",
			Weightage:    marshalJSON([]map[string]interface{}{{"label": "Mathematics", "marks": 50, "color": "bg-brand-500", "width": "35%"}, {"label": "Physics", "marks": 45, "color": "bg-blue-500", "width": "32%"}, {"label": "Chemistry", "marks": 25, "color": "bg-teal-500", "width": "18%"}, {"label": "English & Aptitude", "marks": 20, "color": "bg-purple-500", "width": "15%"}}),
		},
	}

	for _, exam := range exams {
		if err := db.Where(models.Exam{Slug: exam.Slug}).FirstOrCreate(&exam).Error; err != nil {
			log.Printf("Error seeding exam %s: %v", exam.Title, err)
		}
	}
	log.Println("Successfully seeded exams")
	return nil
}

func SeedCourses(db *gorm.DB) error {
	courses := []models.Course{
		{
			Title:         "B.Sc CSIT (Computer Science & IT)",
			ShortTitle:    "BSc CSIT",
			CollegesCount: 0,
			Affiliation:   "TU Affiliated",
			Badges:        marshalJSON([]string{"Top Choice", "High Growth"}),
			Level:         "Bachelor",
			Field:         "IT / Computing",
			Duration:      "4 Years",
			EstFee:        "NPR 4L - 8L",
			Highlights:    marshalJSON([]string{"Merit Scholarships (20 Seats)", "Internship Guaranteed", "Practical Based"}),
			CareerPath:    "Software Engineer, System Analyst, AI Researcher",
			Description:   "Build a strong foundation in software development, networking, databases, and modern IT systems.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 3,50,000",
			PrivateFee:    "NPR 8,50,000 - 12,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"B.Sc CSIT is designed to build strong fundamentals in computing with equal focus on theory and practical implementation.",
				"Students learn software engineering, data structures, databases, networking, and modern development practices through labs and projects.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Foundations", Subjects: []string{"Introduction to IT", "C Programming", "Mathematics I"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Core Skills", Subjects: []string{"OOP in C++", "Discrete Structures", "Digital Logic"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Systems", Subjects: []string{"Data Structures", "Computer Architecture", "Statistics"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Software Core", Subjects: []string{"DBMS", "Operating Systems", "Microprocessor"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Applied Development", Subjects: []string{"Computer Networks", "Web Technology", "Software Engineering"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Advanced Topics", Subjects: []string{"Compiler Design", "E-Governance", "NET Centric Computing"}},
				{Semester: 7, Title: "Semester 7", Subtitle: "Specialization", Subjects: []string{"Artificial Intelligence", "Internship", "Elective I"}},
				{Semester: 8, Title: "Semester 8", Subtitle: "Capstone", Subjects: []string{"Advanced Java", "Project Work", "Elective II"}},
			}),
			Admissions: marshalJSON([]string{"Mark sheets / Transcripts", "Citizenship / ID proof", "Passport-size photos", "Migration and character certificate"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Software Engineer", Icon: "cpu", Color: "emerald"},
				{Title: "Data Analyst", Icon: "chart", Color: "purple"},
				{Title: "Backend Developer", Icon: "database", Color: "blue"},
			}),
		},
		{
			Title:         "BIT (Bachelor in IT)",
			ShortTitle:    "BIT",
			CollegesCount: 0,
			Affiliation:   "Foreign Degree",
			Badges:        marshalJSON([]string{"Global Value", "Industry Ready"}),
			Level:         "Bachelor",
			Field:         "IT / Computing",
			Duration:      "4 Years",
			EstFee:        "NPR 6L - 10L",
			Highlights:    marshalJSON([]string{"Direct Entry", "Job Assistance", "Dual Certification"}),
			CareerPath:    "IT Consultant, Cloud Architect, Web Developer",
			Description:   "Comprehensive program designed to prepare you for a successful global tech career.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 3,50,000",
			PrivateFee:    "NPR 8,50,000 - 12,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"BIT combines software development, cloud, cybersecurity, and product thinking to prepare graduates for modern IT roles.",
				"The curriculum emphasizes industry tools, problem-solving, and portfolio-based learning with internship exposure.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Computing Basics", Subjects: []string{"IT Fundamentals", "Programming Logic", "Business Communication"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Development", Subjects: []string{"Python Programming", "Web Development I", "Mathematics"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Data & Apps", Subjects: []string{"Database Systems", "Java Programming", "Human Computer Interaction"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Infrastructure", Subjects: []string{"Computer Networks", "Operating Systems", "Web Development II"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Enterprise", Subjects: []string{"Software Engineering", "Cloud Fundamentals", "Project Management"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Security", Subjects: []string{"Cyber Security", "Mobile Development", "DevOps Basics"}},
				{Semester: 7, Title: "Semester 7", Subtitle: "Industry Practice", Subjects: []string{"Internship", "Elective I", "System Integration"}},
				{Semester: 8, Title: "Semester 8", Subtitle: "Final Year", Subjects: []string{"Capstone Project", "Elective II", "Professional Ethics"}},
			}),
			Admissions: marshalJSON([]string{"+2 or equivalent transcript", "Valid ID document", "Recent passport-size photos", "Application form and fee receipt"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Cloud Engineer", Icon: "cpu", Color: "emerald"},
				{Title: "Full Stack Developer", Icon: "database", Color: "blue"},
				{Title: "IT Consultant", Icon: "chart", Color: "purple"},
			}),
		},
		{
			Title:         "B.Sc in Data Science & Artificial Intelligence",
			ShortTitle:    "BSc DSAI",
			CollegesCount: 0,
			Affiliation:   "KU Affiliated",
			Badges:        marshalJSON([]string{"Emerging", "AI Focus"}),
			Level:         "Bachelor",
			Field:         "Data Science & AI",
			Duration:      "4 Years",
			EstFee:        "NPR 7L - 12L",
			Highlights:    marshalJSON([]string{"Research Labs", "Industry Mentorship", "AI Projects"}),
			CareerPath:    "Data Scientist, ML Engineer, AI Product Engineer",
			Description:   "A modern interdisciplinary degree combining statistics, computation, and AI systems engineering.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 4,00,000",
			PrivateFee:    "NPR 9,00,000 - 13,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"The B.Sc in Data Science & AI bridges mathematical modeling with practical machine learning engineering.",
				"Students gain expertise in data pipelines, model development, evaluation, and deployment for real-world applications.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Math & Computing", Subjects: []string{"Calculus", "Python for Data Science", "Linear Algebra"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Statistics", Subjects: []string{"Probability", "Data Structures", "Database Systems"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Core ML", Subjects: []string{"Machine Learning I", "Data Visualization", "Optimization"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "AI Systems", Subjects: []string{"Deep Learning", "NLP Basics", "Cloud ML"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Advanced Analytics", Subjects: []string{"Big Data Engineering", "Computer Vision", "MLOps"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Domain Practice", Subjects: []string{"AI Ethics", "Research Methods", "Elective I"}},
				{Semester: 7, Title: "Semester 7", Subtitle: "Industry Integration", Subjects: []string{"Internship", "Elective II", "Case Studies"}},
				{Semester: 8, Title: "Semester 8", Subtitle: "Capstone", Subjects: []string{"Major Project", "Publication Seminar", "Viva"}},
			}),
			Admissions: marshalJSON([]string{"+2 Science/Management with Math", "Entrance / aptitude test", "Academic transcripts", "ID and photos"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Data Scientist", Icon: "database", Color: "blue"},
				{Title: "AI Engineer", Icon: "cpu", Color: "emerald"},
				{Title: "ML Engineer", Icon: "chart", Color: "purple"},
			}),
		},
		{
			Title:         "BE in Civil Engineering",
			ShortTitle:    "BE Civil",
			CollegesCount: 0,
			Affiliation:   "TU/PU/KU Affiliated",
			Badges:        marshalJSON([]string{"High Demand", "Infrastructure"}),
			Level:         "Bachelor",
			Field:         "Engineering",
			Duration:      "4 Years",
			EstFee:        "NPR 5L - 8L",
			Highlights:    marshalJSON([]string{"Practical Labs", "Site Visits", "Industry Projects"}),
			CareerPath:    "Civil Engineer, Structural Engineer, Project Manager",
			Description:   "Comprehensive civil engineering program covering structural, environmental, and infrastructure design.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 4,50,000",
			PrivateFee:    "NPR 7,50,000 - 10,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"BE Civil Engineering provides students with strong technical knowledge in design, construction, and maintenance of infrastructure.",
				"The curriculum includes structural analysis, geotechnical engineering, and transportation engineering.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Foundation", Subjects: []string{"Engineering Mathematics I", "Engineering Physics", "Engineering Chemistry"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Core", Subjects: []string{"Engineering Mathematics II", "Computer Programming", "Engineering Drawing"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Structural Basics", Subjects: []string{"Strength of Materials", "Surveying I", "Fluid Mechanics"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Structural Analysis", Subjects: []string{"Structural Analysis I", "Surveying II", "Concrete Technology"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Design", Subjects: []string{"Steel Structures", "Reinforced Concrete", "Geotechnical Engineering"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Advanced", Subjects: []string{"Foundation Engineering", "Water Resources", "Transportation Engineering"}},
				{Semester: 7, Title: "Semester 7", Subtitle: "Project Prep", Subjects: []string{"Environmental Engineering", "Elective I", "Minor Project"}},
				{Semester: 8, Title: "Semester 8", Subtitle: "Capstone", Subjects: []string{"Major Project", "Professional Practice", "Viva"}},
			}),
			Admissions: marshalJSON([]string{"+2 Science with Math", "IOE Entrance Exam", "Academic transcripts", "ID proof"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Civil Engineer", Icon: "building", Color: "emerald"},
				{Title: "Structural Engineer", Icon: "cube", Color: "blue"},
				{Title: "Project Manager", Icon: "briefcase", Color: "purple"},
			}),
		},
		{
			Title:         "BE in Computer Engineering",
			ShortTitle:    "BE Computer",
			CollegesCount: 0,
			Affiliation:   "TU/PU/KU Affiliated",
			Badges:        marshalJSON([]string{"Top Choice", "High Salary"}),
			Level:         "Bachelor",
			Field:         "Engineering",
			Duration:      "4 Years",
			EstFee:        "NPR 6L - 10L",
			Highlights:    marshalJSON([]string{"Coding Labs", "Tech Projects", "Industry Internships"}),
			CareerPath:    "Software Developer, Systems Engineer, Tech Lead",
			Description:   "Computer engineering program combining hardware and software design with practical development skills.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 5,00,000",
			PrivateFee:    "NPR 8,00,000 - 12,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"BE Computer Engineering covers software development, computer architecture, embedded systems, and networking.",
				"Students gain hands-on experience with modern programming languages and industry tools.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Foundation", Subjects: []string{"Engineering Mathematics I", "Programming Fundamentals", "Physics"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Core", Subjects: []string{"Data Structures", "Digital Logic", "Mathematics II"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Systems", Subjects: []string{"Object Oriented Programming", "Microprocessors", "Discrete Mathematics"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Architecture", Subjects: []string{"Computer Architecture", "Database Systems", "Operating Systems"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Networks", Subjects: []string{"Computer Networks", "Software Engineering", "Artificial Intelligence"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Advanced", Subjects: []string{"Embedded Systems", "Web Engineering", "Elective I"}},
				{Semester: 7, Title: "Semester 7", Subtitle: "Specialization", Subjects: []string{"Cloud Computing", "Cyber Security", "Minor Project"}},
				{Semester: 8, Title: "Semester 8", Subtitle: "Capstone", Subjects: []string{"Major Project", "Professional Practice", "Viva"}},
			}),
			Admissions: marshalJSON([]string{"+2 Science with Math", "IOE Entrance Exam", "Academic transcripts", "ID proof"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Software Developer", Icon: "code", Color: "blue"},
				{Title: "Systems Engineer", Icon: "server", Color: "emerald"},
				{Title: "Tech Lead", Icon: "users", Color: "purple"},
			}),
		},
		{
			Title:         "BBA (Bachelor of Business Administration)",
			ShortTitle:    "BBA",
			CollegesCount: 0,
			Affiliation:   "TU/PU/KU Affiliated",
			Badges:        marshalJSON([]string{"Management", "Leadership"}),
			Level:         "Bachelor",
			Field:         "Business & Management",
			Duration:      "4 Years",
			EstFee:        "NPR 3L - 6L",
			Highlights:    marshalJSON([]string{"Industry Exposure", "Case Studies", "Internship"}),
			CareerPath:    "Business Manager, Marketing Executive, Entrepreneur",
			Description:   "Comprehensive business administration degree covering management, finance, marketing, and operations.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 2,50,000",
			PrivateFee:    "NPR 4,50,000 - 7,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"BBA program develops leadership and managerial skills with practical business knowledge.",
				"Students learn through case studies, projects, and industry interactions.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Foundation", Subjects: []string{"Principles of Management", "Business Mathematics", "Financial Accounting I"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Core", Subjects: []string{"Business Economics", "Financial Accounting II", "Business Communication"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Management", Subjects: []string{"Organizational Behavior", "Marketing Management", "Cost Accounting"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Business", Subjects: []string{"Human Resource Management", "Business Statistics", "Financial Management"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Operations", Subjects: []string{"Operations Management", "Business Research Methods", "Management Information Systems"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Strategy", Subjects: []string{"Strategic Management", "Business Ethics", "International Business"}},
				{Semester: 7, Title: "Semester 7", Subtitle: "Specialization", Subjects: []string{"Elective I", "Summer Internship", "Business Project"}},
				{Semester: 8, Title: "Semester 8", Subtitle: "Capstone", Subjects: []string{"Comprehensive Project", "Entrepreneurship", "Viva"}},
			}),
			Admissions: marshalJSON([]string{"+2 in any stream", "CMAT entrance (for KU/PU)", "Academic transcripts", "ID proof"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Business Manager", Icon: "briefcase", Color: "blue"},
				{Title: "Marketing Executive", Icon: "trending-up", Color: "emerald"},
				{Title: "Entrepreneur", Icon: "lightbulb", Color: "purple"},
			}),
		},
		{
			Title:         "MBA (Master of Business Administration)",
			ShortTitle:    "MBA",
			CollegesCount: 0,
			Affiliation:   "TU/PU/KU Affiliated",
			Badges:        marshalJSON([]string{"Executive", "Leadership"}),
			Level:         "Master",
			Field:         "Business & Management",
			Duration:      "2 Years",
			EstFee:        "NPR 5L - 8L",
			Highlights:    marshalJSON([]string{"Leadership Training", "Industry Projects", "Networking"}),
			CareerPath:    "Senior Manager, Director, CEO",
			Description:   "Advanced management program developing strategic thinking and leadership skills.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 4,00,000",
			PrivateFee:    "NPR 6,50,000 - 12,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Master's Degree",
			About: marshalJSON([]string{
				"MBA prepares students for senior management and leadership positions in business and organizations.",
				"The curriculum covers strategic management, finance, marketing, and organizational leadership.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Core", Subjects: []string{"Managerial Economics", "Accounting for Managers", "Organizational Behavior"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Advanced", Subjects: []string{"Financial Management", "Marketing Management", "Research Methods"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Strategy", Subjects: []string{"Strategic Management", "Business Ethics", "International Business"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Capstone", Subjects: []string{"Major Project", "Comprehensive Viva", "Electives"}},
			}),
			Admissions: marshalJSON([]string{"Bachelor's degree (any field)", "GMAT/CMAT score", "Work experience preferred", "Interview"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Senior Manager", Icon: "briefcase", Color: "blue"},
				{Title: "Director", Icon: "users", Color: "emerald"},
				{Title: "Consultant", Icon: "compass", Color: "purple"},
			}),
		},
		{
			Title:         "BCA (Bachelor of Computer Application)",
			ShortTitle:    "BCA",
			CollegesCount: 0,
			Affiliation:   "TU/PU Affiliated",
			Badges:        marshalJSON([]string{"IT Career", "Programming"}),
			Level:         "Bachelor",
			Field:         "IT / Computing",
			Duration:      "4 Years",
			EstFee:        "NPR 3L - 6L",
			Highlights:    marshalJSON([]string{"Coding Skills", "Practical Projects", "Job Ready"}),
			CareerPath:    "Software Developer, Web Developer, App Developer",
			Description:   "Computer applications degree focusing on software development and IT skills.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 2,80,000",
			PrivateFee:    "NPR 5,00,000 - 8,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"BCA provides comprehensive knowledge in computer applications, programming, and software development.",
				"Students learn multiple programming languages and gain practical development experience.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Foundation", Subjects: []string{"Introduction to IT", "C Programming", "Mathematics I"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Programming", Subjects: []string{"C++ Programming", "Data Structures", "Math II"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Web Basics", Subjects: []string{"HTML/CSS", "JavaScript", "Database"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Application Dev", Subjects: []string{"Java Programming", "PHP", "Software Engineering"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Advanced", Subjects: []string{"ASP.NET", "Python", "Mobile Development"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Enterprise", Subjects: []string{"Cloud Computing", "Cybersecurity", "Project I"}},
				{Semester: 7, Title: "Semester 7", Subtitle: "Specialization", Subjects: []string{"AI/ML Basics", "Elective I", "Project II"}},
				{Semester: 8, Title: "Semester 8", Subtitle: "Capstone", Subjects: []string{"Major Project", "Professional Practice", "Viva"}},
			}),
			Admissions: marshalJSON([]string{"+2 in any stream", "Entrance test (some colleges)", "Academic transcripts", "ID proof"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Software Developer", Icon: "code", Color: "blue"},
				{Title: "Web Developer", Icon: "globe", Color: "emerald"},
				{Title: "App Developer", Icon: "smartphone", Color: "purple"},
			}),
		},
		{
			Title:         "BBS (Bachelor of Business Studies)",
			ShortTitle:    "BBS",
			CollegesCount: 0,
			Affiliation:   "TU Affiliated",
			Badges:        marshalJSON([]string{"Affordable", "Career Focused"}),
			Level:         "Bachelor",
			Field:         "Business & Management",
			Duration:      "4 Years",
			EstFee:        "NPR 2L - 4L",
			Highlights:    marshalJSON([]string{"Affordable Fees", "Wide Colleges", "Good Foundation"}),
			CareerPath:    "Accountant, Business Analyst, Manager",
			Description:   "Business studies degree providing fundamental knowledge in commerce and business.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 1,50,000",
			PrivateFee:    "NPR 3,00,000 - 5,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"BBS is a four-year program offering comprehensive knowledge in business and commerce.",
				"Students develop skills in accounting, economics, and business management.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Foundation", Subjects: []string{"Principles of Management", "Financial Accounting", "Business Mathematics"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Core", Subjects: []string{"Business Economics", "Cost Accounting", "Business Communication"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Business", Subjects: []string{"Organizational Behavior", "Marketing", "Taxation"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Advanced", Subjects: []string{"Financial Management", "HRM", "Business Statistics"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Specialized", Subjects: []string{"Business Law", "Research Methods", "Elective I"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Strategy", Subjects: []string{"Strategic Management", "International Business", "Project"}},
			}),
			Admissions: marshalJSON([]string{"+2 in any stream", "Academic transcripts", "ID proof", "Photos"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Accountant", Icon: "calculator", Color: "blue"},
				{Title: "Business Analyst", Icon: "chart", Color: "emerald"},
				{Title: "Manager", Icon: "briefcase", Color: "purple"},
			}),
		},
		{
			Title:         "BHM (Bachelor of Hotel Management)",
			ShortTitle:    "BHM",
			CollegesCount: 0,
			Affiliation:   "TU/PU Affiliated",
			Badges:        marshalJSON([]string{"Tourism", "Hospitality"}),
			Level:         "Bachelor",
			Field:         "Hospitality & Tourism",
			Duration:      "4 Years",
			EstFee:        "NPR 4L - 7L",
			Highlights:    marshalJSON([]string{"Practical Training", "Hotel Internship", "Global Careers"}),
			CareerPath:    "Hotel Manager, Restaurant Manager, Tourism Director",
			Description:   "Hotel management program covering hospitality operations, food service, and tourism.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 3,00,000",
			PrivateFee:    "NPR 5,00,000 - 8,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"BHM prepares students for managerial positions in hotels, restaurants, and tourism industry.",
				"The program includes practical training in hospitality operations and culinary arts.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Foundation", Subjects: []string{"Introduction to Hospitality", "Food Production", "Front Office"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Operations", Subjects: []string{"Food & Beverage Service", "Housekeeping", "Travel & Tourism"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Management", Subjects: []string{"Hotel Accounting", "Marketing for Hospitality", "Human Resources"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Advanced", Subjects: []string{"Food Safety", "Event Management", "Revenue Management"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Specialization", Subjects: []string{"Strategic Management", "Elective I", "Industrial Training"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Capstone", Subjects: []string{"Major Project", "Professional Practice", "Viva"}},
			}),
			Admissions: marshalJSON([]string{"+2 in any stream", "Personal interview", "Academic transcripts", "ID proof"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Hotel Manager", Icon: "building", Color: "blue"},
				{Title: "Restaurant Manager", Icon: "utensils", Color: "emerald"},
				{Title: "Tourism Director", Icon: "map", Color: "purple"},
			}),
		},
		{
			Title:         "MBBS (Bachelor of Medicine & Bachelor of Surgery)",
			ShortTitle:    "MBBS",
			CollegesCount: 0,
			Affiliation:   "KU Affiliated",
			Badges:        marshalJSON([]string{"Medical", "Healthcare"}),
			Level:         "Bachelor",
			Field:         "Medical & Health Sciences",
			Duration:      "5.5 Years",
			EstFee:        "NPR 35L - 50L",
			Highlights:    marshalJSON([]string{"Clinical Training", "Hospital Rotation", "Medical License"}),
			CareerPath:    "Doctor, Medical Officer, Specialist",
			Description:   "Medical degree program training students to become qualified doctors and medical professionals.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 15,00,000",
			PrivateFee:    "NPR 40,00,000 - 60,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Medical Degree",
			About: marshalJSON([]string{
				"MBBS is a comprehensive medical program covering pre-clinical, para-clinical, and clinical subjects.",
				"Students undergo extensive hospital training and practical exposure.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Year 1", Subtitle: "Foundation", Subjects: []string{"Anatomy", "Physiology", "Biochemistry"}},
				{Semester: 2, Title: "Year 2", Subtitle: "Pre-Clinical", Subjects: []string{"Pharmacology", "Pathology", "Microbiology"}},
				{Semester: 3, Title: "Year 3", Subtitle: "Para-Clinical", Subjects: []string{"Community Medicine", "Forensic Medicine", "ENT", "Ophthalmology"}},
				{Semester: 4, Title: "Year 4 Part 1", Subtitle: "Clinical I", Subjects: []string{"Medicine I", "Surgery I", "Obstetrics & Gynecology"}},
				{Semester: 5, Title: "Year 4 Part 2", Subtitle: "Clinical II", Subjects: []string{"Medicine II", "Surgery II", "Pediatrics", "Orthopedics"}},
				{Semester: 6, Title: "Year 5", Subtitle: "Internship", Subjects: []string{"Rotating Internship", "Rural Posting", "Emergency"}},
			}),
			Admissions: marshalJSON([]string{"+2 Science (Biology)", "Entrance Exam", "NEET (for abroad)", "ID proof"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Doctor", Icon: "heart", Color: "red"},
				{Title: "Medical Officer", Icon: "plus", Color: "blue"},
				{Title: "Specialist", Icon: "stethoscope", Color: "emerald"},
			}),
		},
		{
			Title:         "BDS (Bachelor of Dental Surgery)",
			ShortTitle:    "BDS",
			CollegesCount: 0,
			Affiliation:   "KU Affiliated",
			Badges:        marshalJSON([]string{"Dental", "Healthcare"}),
			Level:         "Bachelor",
			Field:         "Medical & Health Sciences",
			Duration:      "5 Years",
			EstFee:        "NPR 18L - 25L",
			Highlights:    marshalJSON([]string{"Dental Training", "Clinical Practice", "Dental License"}),
			CareerPath:    "Dentist, Dental Surgeon, Oral Specialist",
			Description:   "Dental surgery program training students in oral health and dental care.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 8,00,000",
			PrivateFee:    "NPR 20,00,000 - 30,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Dental Degree",
			About: marshalJSON([]string{
				"BDS covers dental anatomy, oral pathology, and surgical procedures in dentistry.",
				"Students gain hands-on experience in dental clinics and hospitals.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Year 1", Subtitle: "Foundation", Subjects: []string{"Anatomy", "Physiology", "Biochemistry", "Dental Materials"}},
				{Semester: 2, Title: "Year 2", Subtitle: "Pre-Clinical", Subjects: []string{"General Pathology", "Microbiology", "Dental Anatomy"}},
				{Semester: 3, Title: "Year 3", Subtitle: "Para-Clinical", Subjects: []string{"General Surgery", "General Medicine", "Oral Pathology"}},
				{Semester: 4, Title: "Year 4", Subtitle: "Clinical", Subjects: []string{"Conservative Dentistry", "Oral Surgery", "Orthodontics", "Prosthodontics"}},
				{Semester: 5, Title: "Year 5", Subtitle: "Internship", Subjects: []string{"Clinical Training", "Rural Posting", "Emergency"}},
			}),
			Admissions: marshalJSON([]string{"+2 Science (Biology)", "Entrance Exam", "Academic transcripts", "ID proof"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Dentist", Icon: "tooth", Color: "blue"},
				{Title: "Dental Surgeon", Icon: "scissors", Color: "emerald"},
				{Title: "Oral Specialist", Icon: "plus", Color: "purple"},
			}),
		},
		{
			Title:         "B.Sc Nursing",
			ShortTitle:    "BSc Nursing",
			CollegesCount: 0,
			Affiliation:   "KU Affiliated",
			Badges:        marshalJSON([]string{"Nursing", "Healthcare"}),
			Level:         "Bachelor",
			Field:         "Medical & Health Sciences",
			Duration:      "4 Years",
			EstFee:        "NPR 5L - 8L",
			Highlights:    marshalJSON([]string{"Clinical Training", "Hospital Placement", "Nursing License"}),
			CareerPath:    "Nurse, Clinical Nurse, Nurse Manager",
			Description:   "Nursing program preparing students for professional nursing practice in healthcare.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 3,00,000",
			PrivateFee:    "NPR 6,00,000 - 10,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"B.Sc Nursing combines theoretical knowledge with clinical practice in patient care.",
				"Students train in hospitals and community health settings.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Foundation", Subjects: []string{"Anatomy & Physiology", "Nursing Fundamentals", "Biochemistry"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Core", Subjects: []string{"Nursing Theory", "Community Health", "Pharmacology"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Clinical I", Subjects: []string{"Medical Surgical Nursing I", "Psychiatric Nursing", "Research"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Clinical II", Subjects: []string{"Medical Surgical Nursing II", "Pediatric Nursing", "Management"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Specialization", Subjects: []string{"Community Health Nursing", "Elective", "Clinical Practice"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Internship", Subjects: []string{"Comprehensive Internship", "Rural Health", "Viva"}},
			}),
			Admissions: marshalJSON([]string{"+2 Science (Biology)", "Entrance Exam", "Academic transcripts", "ID proof"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Nurse", Icon: "heart", Color: "red"},
				{Title: "Clinical Nurse", Icon: "plus", Color: "blue"},
				{Title: "Nurse Manager", Icon: "users", Color: "emerald"},
			}),
		},
		{
			Title:         "LLB (Bachelor of Law)",
			ShortTitle:    "LLB",
			CollegesCount: 0,
			Affiliation:   "TU Affiliated",
			Badges:        marshalJSON([]string{"Law", "Legal"}),
			Level:         "Bachelor",
			Field:         "Law & Legal Studies",
			Duration:      "4 Years",
			EstFee:        "NPR 2L - 5L",
			Highlights:    marshalJSON([]string{"Moot Court", "Legal Aid", "Internship"}),
			CareerPath:    "Lawyer, Legal Advisor, Judge",
			Description:   "Law degree program covering Nepali legal system, constitutional law, and professional ethics.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 1,80,000",
			PrivateFee:    "NPR 3,50,000 - 6,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"LLB provides comprehensive legal education covering substantive and procedural law.",
				"Students gain practical experience through moot courts and legal aid clinics.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Foundation", Subjects: []string{"Legal Method", "Constitutional Law I", "Law of Torts"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Core", Subjects: []string{"Constitutional Law II", "Contract Law", "Criminal Law I"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Substantive", Subjects: []string{"Criminal Law II", "Property Law", "Family Law"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Business Law", Subjects: []string{"Company Law", "Labor Law", "Tax Law"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Practice", Subjects: []string{"Civil Procedure", "Criminal Procedure", "Evidence"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Specialization", Subjects: []string{"Professional Ethics", "Elective I", "Moot Court"}},
				{Semester: 7, Title: "Semester 7", Subtitle: "Advanced", Subjects: []string{"International Law", "Human Rights Law", "Project"}},
				{Semester: 8, Title: "Semester 8", Subtitle: "Capstone", Subjects: []string{"Major Project", "Viva", "Internship"}},
			}),
			Admissions: marshalJSON([]string{"+2 in any stream", "Entrance test (some colleges)", "Academic transcripts", "ID proof"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Lawyer", Icon: "scale", Color: "blue"},
				{Title: "Legal Advisor", Icon: "shield", Color: "emerald"},
				{Title: "Judge", Icon: "gavel", Color: "purple"},
			}),
		},
		{
			Title:         "BA (Bachelor of Arts)",
			ShortTitle:    "BA",
			CollegesCount: 0,
			Affiliation:   "TU Affiliated",
			Badges:        marshalJSON([]string{"Humanities", "Liberal Arts"}),
			Level:         "Bachelor",
			Field:         "Arts & Humanities",
			Duration:      "4 Years",
			EstFee:        "NPR 1L - 3L",
			Highlights:    marshalJSON([]string{"Wide Subjects", "Critical Thinking", "Communication"}),
			CareerPath:    "Teacher, Writer, Civil Servant",
			Description:   "Liberal arts degree offering diverse subjects in humanities and social sciences.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 80,000",
			PrivateFee:    "NPR 2,00,000 - 4,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"BA provides broad-based education in humanities, social sciences, and liberal arts.",
				"Students develop critical thinking, communication, and analytical skills.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Foundation", Subjects: []string{"English I", "Nepali I", "History"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Core", Subjects: []string{"English II", "Nepali II", "Political Science"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Arts", Subjects: []string{"English III", "Sociology", "Economics"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Advanced", Subjects: []string{"English IV", "Philosophy", "Elective I"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Specialization", Subjects: []string{"Major Subject I", "Elective II", "Research Methods"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Capstone", Subjects: []string{"Major Subject II", "Project", "Viva"}},
			}),
			Admissions: marshalJSON([]string{"+2 in any stream", "Academic transcripts", "ID proof", "Photos"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Teacher", Icon: "book", Color: "blue"},
				{Title: "Writer", Icon: "pen", Color: "emerald"},
				{Title: "Civil Servant", Icon: "building", Color: "purple"},
			}),
		},
		{
			Title:         "B.Ed (Bachelor of Education)",
			ShortTitle:    "B.Ed",
			CollegesCount: 0,
			Affiliation:   "TU Affiliated",
			Badges:        marshalJSON([]string{"Teaching", "Education"}),
			Level:         "Bachelor",
			Field:         "Education",
			Duration:      "4 Years",
			EstFee:        "NPR 2L - 4L",
			Highlights:    marshalJSON([]string{"Teaching Practice", "School Internship", "Teacher License"}),
			CareerPath:    "Teacher, Education Officer, Principal",
			Description:   "Teacher education program preparing students for teaching careers in schools.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 1,50,000",
			PrivateFee:    "NPR 3,00,000 - 5,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"B.Ed combines pedagogical theory with practical teaching experience.",
				"Students learn teaching methodologies, curriculum development, and classroom management.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Foundation", Subjects: []string{"Foundation of Education", "Child Psychology", "Educational Sociology"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Pedagogy", Subjects: []string{"Teaching Methods", "Educational Technology", "School Management"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Practice", Subjects: []string{"Pedagogical Content", "Assessment", "Internship I"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Advanced", Subjects: []string{"Curriculum Development", "Research Methods", "Inclusive Education"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Specialization", Subjects: []string{"Major Methods", "Elective", "Internship II"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Capstone", Subjects: []string{"Major Project", "Viva", "School Experience"}},
			}),
			Admissions: marshalJSON([]string{"+2 in any stream", "Bachelor's degree (for 2-year)", "Academic transcripts", "ID proof"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Teacher", Icon: "book", Color: "blue"},
				{Title: "Education Officer", Icon: "briefcase", Color: "emerald"},
				{Title: "Principal", Icon: "building", Color: "purple"},
			}),
		},
		{
			Title:         "B.Sc in Environmental Science",
			ShortTitle:    "BSc Env",
			CollegesCount: 0,
			Affiliation:   "PU Affiliated",
			Badges:        marshalJSON([]string{"Environment", "Sustainability"}),
			Level:         "Bachelor",
			Field:         "Science",
			Duration:      "4 Years",
			EstFee:        "NPR 3L - 6L",
			Highlights:    marshalJSON([]string{"Field Work", "Research Projects", "Sustainability Focus"}),
			CareerPath:    "Environmentalist, Conservationist, Research Scientist",
			Description:   "Environmental science program focusing on ecology, conservation, and sustainability.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 2,50,000",
			PrivateFee:    "NPR 4,80,000 - 7,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"B.Sc Environmental Science covers ecology, environmental chemistry, and conservation biology.",
				"Students gain practical experience through field trips and research projects.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Foundation", Subjects: []string{"Environmental Chemistry", "Ecology I", "Mathematics"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Core", Subjects: []string{"Ecology II", "Environmental Physics", "Biodiversity"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Applied", Subjects: []string{"Environmental Microbiology", "GIS", "Statistics"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Management", Subjects: []string{"Environmental Management", "Hydrology", "Waste Management"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Specialization", Subjects: []string{"Climate Science", "Elective I", "Field Work"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Capstone", Subjects: []string{"Research Project", "Viva", "Internship"}},
			}),
			Admissions: marshalJSON([]string{"+2 Science", "Academic transcripts", "ID proof", "Entrance test (some)"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Environmentalist", Icon: "leaf", Color: "green"},
				{Title: "Conservationist", Icon: "tree", Color: "emerald"},
				{Title: "Research Scientist", Icon: "flask", Color: "blue"},
			}),
		},
		{
			Title:         "BSW (Bachelor of Social Work)",
			ShortTitle:    "BSW",
			CollegesCount: 0,
			Affiliation:   "TU Affiliated",
			Badges:        marshalJSON([]string{"Social Work", "Community"}),
			Level:         "Bachelor",
			Field:         "Social Work",
			Duration:      "4 Years",
			EstFee:        "NPR 2L - 4L",
			Highlights:    marshalJSON([]string{"Field Practice", "Community Work", "Social Impact"}),
			CareerPath:    "Social Worker, Community Manager, NGO Director",
			Description:   "Social work program preparing students for professional social work practice.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 1,20,000",
			PrivateFee:    "NPR 3,00,000 - 5,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Bachelor's Degree",
			About: marshalJSON([]string{
				"BSW combines social work theory with practical field experience in community settings.",
				"Students learn casework, group work, and community organization.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Foundation", Subjects: []string{"Introduction to Social Work", "Sociology I", "Psychology I"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Core", Subjects: []string{"Social Work Methods", "Sociology II", "Psychology II"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Practice", Subjects: []string{"Casework", "Field Practice I", "Social Policy"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Community", Subjects: []string{"Community Organization", "Group Work", "Research Methods"}},
				{Semester: 5, Title: "Semester 5", Subtitle: "Advanced", Subjects: []string{"Human Rights", "Elective I", "Field Practice II"}},
				{Semester: 6, Title: "Semester 6", Subtitle: "Capstone", Subjects: []string{"Major Project", "Viva", "Internship"}},
			}),
			Admissions: marshalJSON([]string{"+2 in any stream", "Academic transcripts", "ID proof", "Personal interview"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Social Worker", Icon: "users", Color: "blue"},
				{Title: "Community Manager", Icon: "home", Color: "emerald"},
				{Title: "NGO Director", Icon: "heart", Color: "purple"},
			}),
		},
		{
			Title:         "MBS (Master of Business Studies)",
			ShortTitle:    "MBS",
			CollegesCount: 0,
			Affiliation:   "TU Affiliated",
			Badges:        marshalJSON([]string{"Postgraduate", "Management"}),
			Level:         "Master",
			Field:         "Business & Management",
			Duration:      "2 Years",
			EstFee:        "NPR 3L - 5L",
			Highlights:    marshalJSON([]string{"Research Focus", "Specialization", "Thesis"}),
			CareerPath:    "Senior Manager, Business Analyst, Researcher",
			Description:   "Master's in business studies with focus on research and specialized business knowledge.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 2,50,000",
			PrivateFee:    "NPR 5,00,000 - 8,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Master's Degree",
			About: marshalJSON([]string{
				"MBS provides advanced business education with emphasis on research and analytical skills.",
				"Students complete a thesis and specialize in their chosen area.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Core", Subjects: []string{"Managerial Economics", "Financial Management", "Marketing Management"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Advanced", Subjects: []string{"Business Research Methods", "Organizational Behavior", "Strategic Management"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Specialization", Subjects: []string{"Elective I", "Elective II", "Research Proposal"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Capstone", Subjects: []string{"Thesis", "Viva", "Comprehensive Exam"}},
			}),
			Admissions: marshalJSON([]string{"Bachelor's degree (any stream)", "Academic transcripts", "Entrance test", "Interview"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Senior Manager", Icon: "briefcase", Color: "blue"},
				{Title: "Business Analyst", Icon: "chart", Color: "emerald"},
				{Title: "Researcher", Icon: "search", Color: "purple"},
			}),
		},
		{
			Title:         "MSc in Computer Science",
			ShortTitle:    "MSc CS",
			CollegesCount: 0,
			Affiliation:   "KU Affiliated",
			Badges:        marshalJSON([]string{"Research", "Advanced Computing"}),
			Level:         "Master",
			Field:         "IT / Computing",
			Duration:      "2 Years",
			EstFee:        "NPR 5L - 8L",
			Highlights:    marshalJSON([]string{"Research Projects", "Advanced Labs", "Thesis"}),
			CareerPath:    "Research Scientist, Tech Lead, Professor",
			Description:   "Advanced computer science program with focus on research and specialized computing areas.",
			Location:      "Available in Nepal",
			GovtFee:       "NPR 3,50,000",
			PrivateFee:    "NPR 7,00,000 - 10,00,000",
			Mode:          "On-Campus",
			DegreeLabel:   "Master's Degree",
			About: marshalJSON([]string{
				"MSc Computer Science provides advanced knowledge in computing research and development.",
				"Students complete research thesis in areas like AI, networking, or software engineering.",
			}),
			Curriculum: marshalJSON([]CurriculumSemester{
				{Semester: 1, Title: "Semester 1", Subtitle: "Core", Subjects: []string{"Advanced Algorithms", "Research Methods", "Advanced Operating Systems"}},
				{Semester: 2, Title: "Semester 2", Subtitle: "Advanced", Subjects: []string{"Advanced Database", "Machine Learning", "Elective I"}},
				{Semester: 3, Title: "Semester 3", Subtitle: "Research", Subjects: []string{"Thesis I", "Elective II", "Seminar"}},
				{Semester: 4, Title: "Semester 4", Subtitle: "Capstone", Subjects: []string{"Thesis II", "Viva", "Publication"}},
			}),
			Admissions: marshalJSON([]string{"BSc CSIT/BE Computer/equivalent", "Academic transcripts", "Entrance test", "Interview"}),
			Careers: marshalJSON([]CareerOpportunity{
				{Title: "Research Scientist", Icon: "flask", Color: "blue"},
				{Title: "Tech Lead", Icon: "users", Color: "emerald"},
				{Title: "Professor", Icon: "book", Color: "purple"},
			}),
		},
	}

	for _, course := range courses {
		if err := db.Where("title = ?", course.Title).
			Assign(models.Course{
				ShortTitle:    course.ShortTitle,
				CollegesCount: course.CollegesCount,
				Affiliation:   course.Affiliation,
				Badges:        course.Badges,
				Level:         course.Level,
				Field:         course.Field,
				Duration:      course.Duration,
				EstFee:        course.EstFee,
				Highlights:    course.Highlights,
				CareerPath:    course.CareerPath,
				Description:   course.Description,
				Location:      course.Location,
				GovtFee:       course.GovtFee,
				PrivateFee:    course.PrivateFee,
				Mode:          course.Mode,
				DegreeLabel:   course.DegreeLabel,
				About:         course.About,
				Curriculum:    course.Curriculum,
				Admissions:    course.Admissions,
				Careers:       course.Careers,
			}).
			FirstOrCreate(&course).Error; err != nil {
			log.Printf("Error seeding course %s: %v", course.Title, err)
			return err
		}
	}
	log.Println("Successfully seeded courses")
	return nil
}

func SeedNews(db *gorm.DB) error {
	news := []models.News{
		{
			Category: "Academic",
			Title:    "NEB Class 12 Examination Routine 2081 Released",
			Excerpt:  "The National Examination Board (NEB) has officially published the examination schedule for the Grade 12 annual examinations.",
			Content:  "The National Examination Board (NEB) of Nepal has officially announced the routine for the Class 12 board examinations for the academic year 2081/82. The exams are scheduled to begin on Baishakh 14, 2082.",
			Image:    "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=1200",
			Author:   "Academics Desk",
			Date:     "Jan 22, 2025",
			ReadTime: "4 min",
			Source:   "NEB Official",
			Tags:     marshalJSON([]string{"NEB", "Exam", "Class12", "Routine"}),
		},
		{
			Category: "Tech",
			Title:    "AI Integration in Nepali Higher Education",
			Excerpt:  "Top universities in Nepal are starting to integrate AI-driven tools into their curriculum and admission processes.",
			Content:  "A new wave of digital transformation is hitting the educational landscape of Nepal.",
			Image:    "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200",
			Author:   "Tech Reporter",
			Date:     "Jan 18, 2025",
			ReadTime: "6 min",
			Source:   "StudSphere Tech",
			Tags:     marshalJSON([]string{"AI", "Education", "TechTrends", "Nepal"}),
		},
	}

	for _, n := range news {
		if err := db.Where(models.News{Title: n.Title}).FirstOrCreate(&n).Error; err != nil {
			log.Printf("Error seeding news %s: %v", n.Title, err)
		}
	}
	log.Println("Successfully seeded news")
	return nil
}

func SeedEvents(db *gorm.DB) error {
	events := []models.Event{
		{
			Title:      "Virtual Open Day 2025",
			Date:       "March 15, 2025",
			Location:   "Online / Zoom",
			Image:      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=800",
			Interested: 1200,
			Trending:   true,
		},
		{
			Title:      "Engineering Expo",
			Date:       "April 20, 2025",
			Location:   "Pulchowk Campus",
			Image:      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=800",
			Interested: 3500,
			Trending:   true,
		},
	}

	for _, event := range events {
		if err := db.Where(models.Event{Title: event.Title}).FirstOrCreate(&event).Error; err != nil {
			log.Printf("Error seeding event %s: %v", event.Title, err)
		}
	}
	log.Println("Successfully seeded events")
	return nil
}
