package seeder

import (
	"log"
	"strings"

	"studsphere/backend/internal/college"
	"studsphere/backend/internal/education"
	"studsphere/backend/internal/university"

	"gorm.io/gorm"
)

func ClearAcademicData(db *gorm.DB) error {
	if err := db.Unscoped().Where("1 = 1").Delete(&education.CollegeUniversityCourse{}).Error; err != nil {
		return err
	}
	if err := db.Unscoped().Where("1 = 1").Delete(&college.College{}).Error; err != nil {
		return err
	}
	if err := db.Unscoped().Where("1 = 1").Delete(&education.Course{}).Error; err != nil {
		return err
	}
	if err := db.Unscoped().Where("1 = 1").Delete(&education.Exam{}).Error; err != nil {
		return err
	}
	if err := db.Unscoped().Where("1 = 1").Delete(&education.News{}).Error; err != nil {
		return err
	}
	if err := db.Unscoped().Where("1 = 1").Delete(&education.Event{}).Error; err != nil {
		return err
	}
	log.Println("Cleared academic seed data")
	return nil
}

func SeedAcademicColleges(db *gorm.DB) error {
	var universities []university.University
	if err := db.Find(&universities).Error; err != nil {
		return err
	}

	universityByName := map[string]uint{}
	for _, uni := range universities {
		universityByName[strings.ToLower(uni.Name)] = uni.ID
	}

	lookupUniversityID := func(name string) uint {
		if id, ok := universityByName[strings.ToLower(name)]; ok {
			return id
		}
		return 0
	}

	colleges := []college.College{
		{
			UniversityID:     lookupUniversityID("Tribhuvan University"),
			Name:             "St. Xavier's Secondary School",
			FullName:         "St. Xavier's Secondary School, Maitighar",
			Location:         "Kathmandu",
			Affiliation:      "Tribhuvan University",
			CollegeType:      "Private",
			Verified:         true,
			Popular:          true,
			Featured:         true,
			Rating:           4.7,
			Reviews:          421,
			Programs:         3,
			Description:      "A leading +2 college with Science and Management streams.",
			Website:          "sxc.edu.np",
			Email:            "info@sxc.edu.np",
			Phone:            "+977-1-4791000",
			ImageURL:         "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=1400&auto=format&fit=crop",
			FeaturedPrograms: marshalJSON([]string{"+2 Science", "+2 Management", "A Level"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "+2 Science", Category: "Plus2", Duration: "2 Years", Color: "blue"}, {Name: "+2 Management", Category: "Plus2", Duration: "2 Years", Color: "emerald"}, {Name: "A Level - Science", Category: "A Level", Duration: "2 Years", Color: "indigo"}}),
			Courses:          marshalJSON([]Course{{Name: "+2 Science", Level: "+2", Duration: "2 Years", Fees: "NPR 2,80,000", Focus: "STEM preparation"}, {Name: "+2 Management", Level: "+2", Duration: "2 Years", Fees: "NPR 2,20,000", Focus: "Business foundation"}, {Name: "A Level", Level: "A Level", Duration: "2 Years", Fees: "NPR 4,50,000", Focus: "International curriculum"}}),
		},
		{
			UniversityID:     lookupUniversityID("Pokhara University"),
			Name:             "NIST College",
			FullName:         "NIST College, Lainchaur",
			Location:         "Kathmandu",
			Affiliation:      "Pokhara University",
			CollegeType:      "Private",
			Verified:         true,
			Popular:          false,
			Featured:         false,
			Rating:           4.3,
			Reviews:          210,
			Programs:         2,
			Description:      "Known for +2 and A-Level academic preparation.",
			Website:          "nist.edu.np",
			Email:            "hello@nist.edu.np",
			Phone:            "+977-1-4529000",
			ImageURL:         "",
			FeaturedPrograms: marshalJSON([]string{"+2 Science", "A Level - Non-Science/Mgmt"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "+2 Science", Category: "Plus2", Duration: "2 Years", Color: "blue"}, {Name: "A Level - Non-Science/Mgmt", Category: "A Level", Duration: "2 Years", Color: "orange"}}),
			Courses:          marshalJSON([]Course{{Name: "+2 Science", Level: "+2", Duration: "2 Years", Fees: "NPR 2,60,000", Focus: "Science stream"}, {Name: "A Level - Non-Science/Mgmt", Level: "A Level", Duration: "2 Years", Fees: "NPR 4,20,000", Focus: "Management and humanities"}}),
		},
		{
			UniversityID:     lookupUniversityID("Tribhuvan University"),
			Name:             "CTEVT Technical Institute Bhaktapur",
			FullName:         "CTEVT Technical Institute, Bhaktapur",
			Location:         "Bhaktapur",
			Affiliation:      "Tribhuvan University",
			CollegeType:      "Public / Govt",
			Verified:         false,
			Popular:          true,
			Featured:         false,
			Rating:           4.1,
			Reviews:          134,
			Programs:         3,
			Description:      "Diploma-focused institute for CTEVT technical programs.",
			Website:          "ctevt.org.np",
			Email:            "info@ctevt.org.np",
			Phone:            "+977-1-6638000",
			ImageURL:         "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=1400&auto=format&fit=crop",
			FeaturedPrograms: marshalJSON([]string{"Diploma in Civil Eng.", "Diploma in Computer Eng.", "PCL Nursing"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "Diploma in Civil Eng.", Category: "Diploma", Duration: "3 Years", Color: "teal"}, {Name: "Diploma in Computer Eng.", Category: "Diploma", Duration: "3 Years", Color: "indigo"}, {Name: "PCL Nursing", Category: "Diploma", Duration: "3 Years", Color: "pink"}}),
			Courses:          marshalJSON([]Course{{Name: "Diploma in Civil Eng.", Level: "Diploma", Duration: "3 Years", Fees: "NPR 1,80,000", Focus: "Civil drafting and site work"}, {Name: "Diploma in Computer Eng.", Level: "Diploma", Duration: "3 Years", Fees: "NPR 2,10,000", Focus: "Hardware and software"}, {Name: "PCL Nursing", Level: "Diploma", Duration: "3 Years", Fees: "NPR 2,40,000", Focus: "Nursing fundamentals"}}),
		},
		{
			UniversityID:     lookupUniversityID("Purbanchal University"),
			Name:             "Lalitpur Vocational College",
			FullName:         "Lalitpur Vocational College",
			Location:         "Lalitpur",
			Affiliation:      "Purbanchal University",
			CollegeType:      "Community",
			Verified:         false,
			Popular:          false,
			Featured:         false,
			Rating:           3.9,
			Reviews:          79,
			Programs:         2,
			Description:      "Community-based diploma and +2 programs.",
			Website:          "lalitpurvoc.edu.np",
			Email:            "contact@lalitpurvoc.edu.np",
			Phone:            "+977-1-5509000",
			ImageURL:         "",
			FeaturedPrograms: marshalJSON([]string{"Diploma / CTEVT", "+2 Management"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "Diploma / CTEVT", Category: "Diploma", Duration: "3 Years", Color: "emerald"}, {Name: "+2 Management", Category: "Plus2", Duration: "2 Years", Color: "blue"}}),
			Courses:          marshalJSON([]Course{{Name: "Diploma / CTEVT", Level: "Diploma", Duration: "3 Years", Fees: "NPR 1,60,000", Focus: "Applied vocational skills"}, {Name: "+2 Management", Level: "+2", Duration: "2 Years", Fees: "NPR 1,40,000", Focus: "Commerce basics"}}),
		},
		{
			UniversityID:     lookupUniversityID("Kathmandu University"),
			Name:             "Apex Higher Secondary School",
			FullName:         "Apex Higher Secondary School, Koteshwor",
			Location:         "Kathmandu",
			Affiliation:      "Kathmandu University",
			CollegeType:      "Private",
			Verified:         true,
			Popular:          true,
			Featured:         false,
			Rating:           4.5,
			Reviews:          256,
			Programs:         2,
			Description:      "Strong +2 Science and +2 Management outcomes with active mentoring.",
			Website:          "apexhss.edu.np",
			Email:            "admission@apexhss.edu.np",
			Phone:            "+977-1-5141000",
			ImageURL:         "https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=1400&auto=format&fit=crop",
			FeaturedPrograms: marshalJSON([]string{"+2 Science", "+2 Management"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "+2 Science", Category: "Plus2", Duration: "2 Years", Color: "blue"}, {Name: "+2 Management", Category: "Plus2", Duration: "2 Years", Color: "emerald"}}),
			Courses:          marshalJSON([]Course{{Name: "+2 Science", Level: "+2", Duration: "2 Years", Fees: "NPR 2,30,000", Focus: "Lab and exam readiness"}, {Name: "+2 Management", Level: "+2", Duration: "2 Years", Fees: "NPR 1,95,000", Focus: "Accounting and business fundamentals"}}),
		},
		{
			UniversityID:     lookupUniversityID("Mid-Western University"),
			Name:             "Surkhet A-Level Academy",
			FullName:         "Surkhet A-Level Academy",
			Location:         "Surkhet",
			Affiliation:      "Mid-Western University",
			CollegeType:      "Community",
			Verified:         false,
			Popular:          false,
			Featured:         false,
			Rating:           3.8,
			Reviews:          58,
			Programs:         1,
			Description:      "Community A-Level institution for science and management pathways.",
			Website:          "surkhetalevel.edu.np",
			Email:            "info@surkhetalevel.edu.np",
			Phone:            "+977-83-520001",
			ImageURL:         "",
			FeaturedPrograms: marshalJSON([]string{"A Level - Science"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "A Level - Science", Category: "A Level", Duration: "2 Years", Color: "indigo"}}),
			Courses:          marshalJSON([]Course{{Name: "A Level - Science", Level: "A Level", Duration: "2 Years", Fees: "NPR 3,80,000", Focus: "University preparation"}}),
		},
		{
			UniversityID:     lookupUniversityID("Far-Western University"),
			Name:             "Kailali Technical Campus",
			FullName:         "Kailali Technical Campus",
			Location:         "Kailali",
			Affiliation:      "Far-Western University",
			CollegeType:      "Public / Govt",
			Verified:         true,
			Popular:          false,
			Featured:         false,
			Rating:           4.0,
			Reviews:          102,
			Programs:         2,
			Description:      "Public technical campus running CTEVT-aligned diploma tracks.",
			Website:          "kailalitech.edu.np",
			Email:            "office@kailalitech.edu.np",
			Phone:            "+977-91-528800",
			ImageURL:         "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?q=80&w=1400&auto=format&fit=crop",
			FeaturedPrograms: marshalJSON([]string{"Diploma in Computer Eng.", "Diploma in Civil Eng."}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "Diploma in Computer Eng.", Category: "Diploma", Duration: "3 Years", Color: "indigo"}, {Name: "Diploma in Civil Eng.", Category: "Diploma", Duration: "3 Years", Color: "teal"}}),
			Courses:          marshalJSON([]Course{{Name: "Diploma in Computer Eng.", Level: "Diploma", Duration: "3 Years", Fees: "NPR 1,95,000", Focus: "Software and networking"}, {Name: "Diploma in Civil Eng.", Level: "Diploma", Duration: "3 Years", Fees: "NPR 1,75,000", Focus: "Survey and construction"}}),
		},
		{
			UniversityID:     lookupUniversityID("Tribhuvan University"),
			Name:             "Bagmati Community College",
			FullName:         "Bagmati Community College, Chitwan",
			Location:         "Chitwan",
			Affiliation:      "Tribhuvan University",
			CollegeType:      "Community",
			Verified:         false,
			Popular:          true,
			Featured:         false,
			Rating:           4.0,
			Reviews:          144,
			Programs:         2,
			Description:      "Accessible +2 options for students across Chitwan district.",
			Website:          "bagmaticc.edu.np",
			Email:            "admissions@bagmaticc.edu.np",
			Phone:            "+977-56-530100",
			ImageURL:         "",
			FeaturedPrograms: marshalJSON([]string{"+2 Management", "+2 Humanities"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "+2 Management", Category: "Plus2", Duration: "2 Years", Color: "blue"}, {Name: "+2 Humanities", Category: "Plus2", Duration: "2 Years", Color: "orange"}}),
			Courses:          marshalJSON([]Course{{Name: "+2 Management", Level: "+2", Duration: "2 Years", Fees: "NPR 1,35,000", Focus: "Business, account, economics"}, {Name: "+2 Humanities", Level: "+2", Duration: "2 Years", Fees: "NPR 1,10,000", Focus: "Social sciences"}}),
		},
		{
			UniversityID:     lookupUniversityID("Pokhara University"),
			Name:             "Pokhara Plus Two Institute",
			FullName:         "Pokhara Plus Two Institute",
			Location:         "Kaski",
			Affiliation:      "Pokhara University",
			CollegeType:      "Private",
			Verified:         true,
			Popular:          true,
			Featured:         true,
			Rating:           4.6,
			Reviews:          312,
			Programs:         3,
			Description:      "High-performing +2 and A-Level preparation in Pokhara valley.",
			Website:          "ppti.edu.np",
			Email:            "hello@ppti.edu.np",
			Phone:            "+977-61-450222",
			ImageURL:         "https://images.unsplash.com/photo-1497486751825-1233686d5d80?q=80&w=1400&auto=format&fit=crop",
			FeaturedPrograms: marshalJSON([]string{"+2 Science", "+2 Management", "A Level - Non-Science/Mgmt"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "+2 Science", Category: "Plus2", Duration: "2 Years", Color: "blue"}, {Name: "+2 Management", Category: "Plus2", Duration: "2 Years", Color: "emerald"}, {Name: "A Level - Non-Science/Mgmt", Category: "A Level", Duration: "2 Years", Color: "orange"}}),
			Courses:          marshalJSON([]Course{{Name: "+2 Science", Level: "+2", Duration: "2 Years", Fees: "NPR 2,70,000", Focus: "Science foundation"}, {Name: "+2 Management", Level: "+2", Duration: "2 Years", Fees: "NPR 2,10,000", Focus: "Commerce and finance"}, {Name: "A Level - Non-Science/Mgmt", Level: "A Level", Duration: "2 Years", Fees: "NPR 3,90,000", Focus: "Global curriculum"}}),
		},
		{
			UniversityID:     lookupUniversityID("Purbanchal University"),
			Name:             "Morang Allied Health College",
			FullName:         "Morang Allied Health College",
			Location:         "Morang",
			Affiliation:      "Purbanchal University",
			CollegeType:      "Constituent",
			Verified:         true,
			Popular:          false,
			Featured:         false,
			Rating:           4.2,
			Reviews:          168,
			Programs:         2,
			Description:      "Allied health diploma tracks with practical hospital exposure.",
			Website:          "moranghealth.edu.np",
			Email:            "contact@moranghealth.edu.np",
			Phone:            "+977-21-470200",
			ImageURL:         "",
			FeaturedPrograms: marshalJSON([]string{"PCL Nursing", "HA (General Medicine)"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "PCL Nursing", Category: "Diploma", Duration: "3 Years", Color: "pink"}, {Name: "HA (General Medicine)", Category: "Diploma", Duration: "3 Years", Color: "teal"}}),
			Courses:          marshalJSON([]Course{{Name: "PCL Nursing", Level: "Diploma", Duration: "3 Years", Fees: "NPR 2,30,000", Focus: "Clinical skills"}, {Name: "HA (General Medicine)", Level: "Diploma", Duration: "3 Years", Fees: "NPR 2,00,000", Focus: "Primary health service"}}),
		},
		{
			UniversityID:     lookupUniversityID("Lincoln University"),
			Name:             "Lincoln International A-Level Centre",
			FullName:         "Lincoln International A-Level Centre",
			Location:         "Lalitpur",
			Affiliation:      "Lincoln University",
			CollegeType:      "Foreign Affiliated",
			Verified:         true,
			Popular:          false,
			Featured:         false,
			Rating:           4.4,
			Reviews:          96,
			Programs:         1,
			Description:      "Foreign-affiliated A-Level center with international pathways.",
			Website:          "lincolnalevel.edu.np",
			Email:            "office@lincolnalevel.edu.np",
			Phone:            "+977-1-5441100",
			ImageURL:         "https://images.unsplash.com/photo-1462530260150-162092dbf011?q=80&w=1400&auto=format&fit=crop",
			FeaturedPrograms: marshalJSON([]string{"A Level - Science"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "A Level - Science", Category: "A Level", Duration: "2 Years", Color: "indigo"}}),
			Courses:          marshalJSON([]Course{{Name: "A Level - Science", Level: "A Level", Duration: "2 Years", Fees: "NPR 5,20,000", Focus: "International standards"}}),
		},
		{
			UniversityID:     lookupUniversityID("London Metropolitan University"),
			Name:             "London Met Foundation College",
			FullName:         "London Met Foundation College, Kathmandu",
			Location:         "Kathmandu",
			Affiliation:      "London Metropolitan University",
			CollegeType:      "Foreign Affiliated",
			Verified:         false,
			Popular:          false,
			Featured:         false,
			Rating:           3.7,
			Reviews:          41,
			Programs:         1,
			Description:      "Foundation and A-Level non-science pathways for international entry.",
			Website:          "londonmetfoundation.edu.np",
			Email:            "admissions@londonmetfoundation.edu.np",
			Phone:            "+977-1-4102000",
			ImageURL:         "",
			FeaturedPrograms: marshalJSON([]string{"A Level - Non-Science/Mgmt"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "A Level - Non-Science/Mgmt", Category: "A Level", Duration: "2 Years", Color: "orange"}}),
			Courses:          marshalJSON([]Course{{Name: "A Level - Non-Science/Mgmt", Level: "A Level", Duration: "2 Years", Fees: "NPR 4,90,000", Focus: "Business and social science track"}}),
		},
		{
			UniversityID:     lookupUniversityID("Agriculture & Forestry University"),
			Name:             "AFU Technical Prep School",
			FullName:         "AFU Technical Prep School",
			Location:         "Chitwan",
			Affiliation:      "Agriculture & Forestry University",
			CollegeType:      "Constituent",
			Verified:         true,
			Popular:          true,
			Featured:         false,
			Rating:           4.2,
			Reviews:          138,
			Programs:         2,
			Description:      "CTEVT and +2 education focused on agriculture and applied sciences.",
			Website:          "afuprep.edu.np",
			Email:            "contact@afuprep.edu.np",
			Phone:            "+977-56-420800",
			ImageURL:         "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=1400&auto=format&fit=crop",
			FeaturedPrograms: marshalJSON([]string{"Diploma / CTEVT", "+2 Science"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "Diploma / CTEVT", Category: "Diploma", Duration: "3 Years", Color: "emerald"}, {Name: "+2 Science", Category: "Plus2", Duration: "2 Years", Color: "blue"}}),
			Courses:          marshalJSON([]Course{{Name: "Diploma / CTEVT", Level: "Diploma", Duration: "3 Years", Fees: "NPR 1,70,000", Focus: "Agriculture and field training"}, {Name: "+2 Science", Level: "+2", Duration: "2 Years", Fees: "NPR 2,10,000", Focus: "Biology and chemistry"}}),
		},
		{
			UniversityID:     lookupUniversityID("Tribhuvan University"),
			Name:             "Janakpur Education Campus",
			FullName:         "Janakpur Education Campus",
			Location:         "Dhanusha",
			Affiliation:      "Tribhuvan University",
			CollegeType:      "Public / Govt",
			Verified:         false,
			Popular:          true,
			Featured:         false,
			Rating:           3.9,
			Reviews:          121,
			Programs:         2,
			Description:      "Public +2 college offering management and education streams.",
			Website:          "janakpuredu.edu.np",
			Email:            "info@janakpuredu.edu.np",
			Phone:            "+977-41-520220",
			ImageURL:         "",
			FeaturedPrograms: marshalJSON([]string{"+2 Management", "+2 Education"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "+2 Management", Category: "Plus2", Duration: "2 Years", Color: "blue"}, {Name: "+2 Education", Category: "Plus2", Duration: "2 Years", Color: "orange"}}),
			Courses:          marshalJSON([]Course{{Name: "+2 Management", Level: "+2", Duration: "2 Years", Fees: "NPR 1,20,000", Focus: "Commerce and economics"}, {Name: "+2 Education", Level: "+2", Duration: "2 Years", Fees: "NPR 1,10,000", Focus: "Teaching fundamentals"}}),
		},
		{
			UniversityID:     lookupUniversityID("Pokhara University"),
			Name:             "Butwal Skill College",
			FullName:         "Butwal Skill College, Rupandehi",
			Location:         "Rupandehi",
			Affiliation:      "Pokhara University",
			CollegeType:      "Private",
			Verified:         true,
			Popular:          false,
			Featured:         false,
			Rating:           4.1,
			Reviews:          88,
			Programs:         2,
			Description:      "Job-ready diploma tracks for engineering and tourism sectors.",
			Website:          "butwalskill.edu.np",
			Email:            "admin@butwalskill.edu.np",
			Phone:            "+977-71-530510",
			ImageURL:         "https://images.unsplash.com/photo-1529074963764-98f45c47344b?q=80&w=1400&auto=format&fit=crop",
			FeaturedPrograms: marshalJSON([]string{"Diploma in Civil Eng.", "Hotel Management & Tourism"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "Diploma in Civil Eng.", Category: "Diploma", Duration: "3 Years", Color: "teal"}, {Name: "Hotel Management & Tourism", Category: "Diploma", Duration: "3 Years", Color: "amber"}}),
			Courses:          marshalJSON([]Course{{Name: "Diploma in Civil Eng.", Level: "Diploma", Duration: "3 Years", Fees: "NPR 1,85,000", Focus: "Civil drafting"}, {Name: "Hotel Management & Tourism", Level: "Diploma", Duration: "3 Years", Fees: "NPR 2,10,000", Focus: "Hospitality and service"}}),
		},
		{
			UniversityID:     lookupUniversityID("Purbanchal University"),
			Name:             "Jhapa Advanced Secondary",
			FullName:         "Jhapa Advanced Secondary School",
			Location:         "Jhapa",
			Affiliation:      "Purbanchal University",
			CollegeType:      "Community",
			Verified:         false,
			Popular:          false,
			Featured:         false,
			Rating:           3.8,
			Reviews:          67,
			Programs:         2,
			Description:      "Regional +2 provider focused on science and humanities.",
			Website:          "jhapaadvanced.edu.np",
			Email:            "contact@jhapaadvanced.edu.np",
			Phone:            "+977-23-560130",
			ImageURL:         "",
			FeaturedPrograms: marshalJSON([]string{"+2 Science", "+2 Humanities"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "+2 Science", Category: "Plus2", Duration: "2 Years", Color: "blue"}, {Name: "+2 Humanities", Category: "Plus2", Duration: "2 Years", Color: "orange"}}),
			Courses:          marshalJSON([]Course{{Name: "+2 Science", Level: "+2", Duration: "2 Years", Fees: "NPR 1,70,000", Focus: "Science stream"}, {Name: "+2 Humanities", Level: "+2", Duration: "2 Years", Fees: "NPR 1,05,000", Focus: "Social studies"}}),
		},
		{
			UniversityID:     lookupUniversityID("University of the West of England"),
			Name:             "UWE Pathway College Nepal",
			FullName:         "UWE Pathway College Nepal",
			Location:         "Kathmandu",
			Affiliation:      "University of the West of England",
			CollegeType:      "Foreign Affiliated",
			Verified:         true,
			Popular:          false,
			Featured:         true,
			Rating:           4.5,
			Reviews:          73,
			Programs:         1,
			Description:      "International A-Level and foundation pathway to UK partner universities.",
			Website:          "uwepathway.edu.np",
			Email:            "info@uwepathway.edu.np",
			Phone:            "+977-1-4005111",
			ImageURL:         "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?q=80&w=1400&auto=format&fit=crop",
			FeaturedPrograms: marshalJSON([]string{"A Level - Non-Science/Mgmt"}),
			ProgramsList:     marshalJSON([]ProgramDetail{{Name: "A Level - Non-Science/Mgmt", Category: "A Level", Duration: "2 Years", Color: "orange"}}),
			Courses:          marshalJSON([]Course{{Name: "A Level - Non-Science/Mgmt", Level: "A Level", Duration: "2 Years", Fees: "NPR 5,40,000", Focus: "Global pathway and credits"}}),
		},
	}

	for _, item := range colleges {
		record := item
		applyProfileFitDefaults(&record)
		if err := db.Create(&record).Error; err != nil {
			return err
		}
	}

	log.Println("Successfully seeded academic colleges (+2/A level/Diploma only)")
	return nil
}
